### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by spacedome** [spacedome/FEASTSolver.jl#5]
Some goals I am putting forward as I transition this repo from a collection of research algorithms to a sensible library that can be used for solving linear and nonlinear eigenvalue problems. If this library is useful to you, or could be more useful to you, let me know what you think, how the "interface" of these algorithms should work is still up in the air. Despite the name, it will likely include (already sort of does) tools to build any contour based eigensolver, with implementations of Beyn's algorithm (done) and some of the SS methods. 

- [ ] Documentation & code comments (there are none right now, sorry!)
- [ ] Tests & more examples.
- [ ] More complete sparse and iterative support
- [ ] Allow for NEP-PACK problem types (PEP, NEP, etc.), and potentially implement some variant of the NLFEAST algorithm within NEP-PACK if there is interest.
- [ ] Refactor for flexibility (somewhat nebulous, but every part of the algorithms should be modifiable)
- [ ] Some semblance of benchmarking [(BenchmarkTools.jl?)](https://github.com/JuliaCI/BenchmarkTools.jl)
- [ ] Tools for working with contours
- [ ] An additional easy to use "black box" solver interface (if this approach seems useful)
- [ ] Distributed computing (maybe) 
- [ ] Potentially optional dependancied (MUMPS, NEP-PACK, Iterative solver libraries, etc.)

A more philosophical decision is how to trade off readability and flexibility with performance. Initially the implementations here were meant to be simple and educational, but this is better fit by code examples in documentation. I have moved towards practical implementations, not to compete with the FEAST fortran code in raw performance and robustness (which benefit from the many hours put into building it), but instead in the flexibility Julia allows, which should make many kinds of optimizations and modifications possible and easily implemented. For example, the code is already (somewhat) easily adapted to use higher precision floats, or any type with a dense eigenvalue solver.
